### ISSUE TITLE
Hyperparameters in config are the ones achieved results in the paper?

### ISSUE THREAD

**Issue by XingyuJinTI** [taylover-pei/SSDG-CVPR2020#11]
Hi there, I achieved different results with your current config files and three of them are lower performed.

![Screenshot from 2020-09-01 23-03-40](https://user-images.githubusercontent.com/17474067/91910722-7384d480-eca7-11ea-871b-7928e7a04f6f.png)

Mine was like this
![Screenshot from 2020-09-01 23-03-51](https://user-images.githubusercontent.com/17474067/91910744-7c75a600-eca7-11ea-9a4c-d233f54d9af9.png)

I just wonder if Hyperparameters in config are the ones achieved results in the paper? Many thanks

**Comment by 1relia** [comment]
我也遇到这了这个问题
![image](https://user-images.githubusercontent.com/39758541/92591899-4fda1380-f2d1-11ea-88b9-c5ce8c18e841.png)
请问你是默认参数运行的么

**Comment by taylover-pei** [comment]
Sorry for answering late.

The hyperparameters are the same as our original paper. 

Two points need to be confirmed:

1. Did you follow the code prompts and use the specified MTCNN code for face detection and alignment?

2. Is the frames of each video selected for training are the same with us?

If it is due to data processing or experimental environment problems, I suggest you to tune some parameters by yourself to find a set of optimal parameters suitable for your data set and environment.
